from .third_person_descriptive_0_9 import ThirdPersonDescriptive09
from .third_person_descriptive_0_9_1prompt import ThirdPersonDescriptive09_1Shot
from .third_person_descriptive_0_9_2prompt import ThirdPersonDescriptive09_2Shot
from .third_person_descriptive_one_ten import ThirdPersonDescriptiveOneTen
from .third_person_descriptive_one_ten_1prompt import ThirdPersonDescriptiveOneTen_1Shot
from .third_person_descriptive_one_ten_2prompt import ThirdPersonDescriptiveOneTen_2Shot
from .third_person_sys_as_user_0_9 import ThirdPersonSysAsUser09
